apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-static-webapp
  namespace: my-static-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-static-webapp
  template:
    metadata:
      labels:
        app: my-static-webapp
    spec:
      containers:
      - name: my-static-webapp
        image: my_image_name:latest
        ports:
        - containerPort: 80
