apiVersion: v1
kind: Service
metadata:
  name: my-static-webapp-service
  namespace: my-static-webapp
spec:
  selector:
    app: my-static-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Expose the service on a random node port
